[Service]
Environment=
Environment=PUBLIC_BASE_URL=https://token.zasdas.com
Environment=PUBLIC_API_BASE_URL=https://token.zasdas.com
Environment=KEY_PORTAL_HOST=127.0.0.1
Environment=KEY_PORTAL_PORT=18080
